apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: curler
  name: curler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: curler
  template:
    metadata:
      labels:
        run: curler
    spec:
      containers:
      - args:
        - /bin/sh
        image: busybox
        imagePullPolicy: Always
        name: curler
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      restartPolicy: Always
      nodeSelector:
        cloud.google.com/gke-nodepool: "fixed-pool"
